version: "3.1"

services:
  postgres:
    container_name: vocabulary_postgres
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: crep
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  postgres-data:

